DatabaseType: SQLite         ##The database type can be: "MySQL" or "SQLite"
Database: tickets            ##The database name
DatabaseHost: 127.0.0.1      ##The database host address, 127.0.0.1 is localhost
DatabasePort: 3306           ##The database port, 3306 is the defualt port
DatabaseUser: root           ##The username of the database account 
DatabasePassword: 123        ##The password to access the database account

Categories:                  ##The categories a ticket can have
- Grief                      ##Keep this "None" for empty categories
- Admin
- Theft

TicketTitleLength: 15        ##The title length, It shouldn't be very long
TicketDescriptionLength: 100 ##The Description length, shouldn't be very long since it might create GUI overlapping
